[package]
name = "migration"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migration"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.49", features = ["full"] }
sea-orm-migration = { version = "=2.0.0-rc.22", default-features = false, features = [
    "runtime-tokio-rustls",
    "sqlx-sqlite",
] }
