//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use chrono::NaiveDateTime; // ADDED
use sea_orm::entity::prelude::*;
use uuid::Uuid; // ADDED

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid, // CHANGED: String → Uuid
    #[sea_orm(column_type = "Text")]
    pub label: String,
    #[sea_orm(column_type = "Text")]
    pub folder: String,
    #[sea_orm(column_type = "Timestamp")] // ADDED
    pub created_at: NaiveDateTime, // CHANGED: String → NaiveDateTime
    #[sea_orm(column_type = "Timestamp")] // ADDED
    pub updated_at: NaiveDateTime, // CHANGED: String → NaiveDateTime
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub importance_score: i32, // CHANGED: i64 → i32
    pub word_count: i32,       // CHANGED: i64 → i32
    pub session_count: i32,    // CHANGED: i64 → i32
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hierarchical_summaries::Entity")]
    HierarchicalSummaries,
    #[sea_orm(has_many = "super::knowledge_graph_edges::Entity")]
    KnowledgeGraphEdges,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(has_many = "super::semantic_tags::Entity")]
    SemanticTags,
}

impl Related<super::hierarchical_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HierarchicalSummaries.def()
    }
}

impl Related<super::knowledge_graph_edges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeGraphEdges.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::semantic_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SemanticTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
