//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "conversations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub label: String,
    #[sea_orm(column_type = "Text")]
    pub folder: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub importance_score: i64,
    pub word_count: i64,
    pub session_count: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hierarchical_summaries::Entity")]
    HierarchicalSummaries,
    #[sea_orm(has_many = "super::knowledge_graph_edges::Entity")]
    KnowledgeGraphEdges,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(has_many = "super::semantic_tags::Entity")]
    SemanticTags,
}

impl Related<super::hierarchical_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HierarchicalSummaries.def()
    }
}

impl Related<super::knowledge_graph_edges::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeGraphEdges.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::semantic_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SemanticTags.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
