//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use chrono::NaiveDateTime;
use sea_orm::entity::prelude::*;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "hierarchical_summaries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub conversation_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub level: String,
    #[sea_orm(column_type = "Text")]
    pub summary_text: String,
    pub timestamp_range: String, // Keep as String (range format)
    #[sea_orm(column_type = "Timestamp")]
    pub generated_at: NaiveDateTime,
    #[sea_orm(nullable)]
    pub model_used: Option<String>,
    pub token_count: Option<i32>, // CHANGED: i64 → i32
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::conversations::Entity",
        from = "Column::ConversationId",
        to = "super::conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Conversations,
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
