//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "hierarchical_summaries")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub conversation_id: String,
    #[sea_orm(column_type = "Text")]
    pub level: String,
    #[sea_orm(column_type = "Text")]
    pub summary_text: String,
    #[sea_orm(column_type = "Text")]
    pub timestamp_range: String,
    #[sea_orm(column_type = "Text")]
    pub generated_at: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub model_used: Option<String>,
    pub token_count: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::conversations::Entity",
        from = "Column::ConversationId",
        to = "super::conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Conversations,
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
