//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use chrono::NaiveDateTime;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "knowledge_graph_edges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub subject_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub predicate: String, // Keep as String (relationship type)
    #[sea_orm(primary_key, auto_increment = false)]
    pub object_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub conversation_id: Uuid,
    #[sea_orm(column_type = "Timestamp")]
    pub extracted_at: NaiveDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::conversations::Entity",
        from = "Column::ConversationId",
        to = "super::conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Conversations,
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}