//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use chrono::NaiveDateTime; // ADDED
use uuid::Uuid; // ADDED
use serde_json::Value; // ADDED

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid, // CHANGED: String → Uuid
    pub conversation_id: Uuid, // CHANGED: String → Uuid
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Timestamp")] // ADDED
    pub timestamp: NaiveDateTime, // CHANGED: String → NaiveDateTime
    #[sea_orm(nullable)]
    pub embedding_id: Option<String>, // Keep as String (Chroma ID, not UUID)
    #[sea_orm(column_type = "Json", nullable)] // CHANGED: Text → Json
    pub metadata: Option<Value>, // CHANGED: String → Value
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::conversations::Entity",
        from = "Column::ConversationId",
        to = "super::conversations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Conversations,
}

impl Related<super::conversations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Conversations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}